import type {
  AiSystem,
  ClassificationAnswers,
  ClassificationResult,
} from "@/lib/domain/types";
import type { ControlView } from "@/lib/controls";
import type { SystemGapReport } from "@/lib/gap";
import { classificationQuestions } from "@/lib/classifier/questions";

const LEGAL = "This product provides compliance tooling, not legal advice.";

function esc(v: unknown): string {
  return String(v ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function tierColour(tier: string): string {
  return (
    {
      PROHIBITED: "#b91c1c",
      HIGH: "#c2410c",
      LIMITED: "#a16207",
      MINIMAL: "#15803d",
    } as Record<string, string>
  )[tier] ?? "#334155";
}

const BASE_CSS = `
  * { box-sizing: border-box; }
  body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; color: #0f172a; margin: 0; padding: 32px; font-size: 12px; line-height: 1.5; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  h2 { font-size: 15px; margin: 24px 0 8px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
  .muted { color: #64748b; }
  .badge { display: inline-block; color: #fff; padding: 3px 10px; border-radius: 999px; font-weight: 700; font-size: 12px; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; }
  th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid #e2e8f0; vertical-align: top; }
  th { background: #f1f5f9; font-weight: 600; }
  .cite { color: #1f47c2; font-family: ui-monospace, monospace; font-size: 11px; }
  .status-DONE { color: #15803d; font-weight: 600; }
  .status-MISSING { color: #b91c1c; font-weight: 600; }
  .status-IN_PROGRESS { color: #a16207; font-weight: 600; }
  .status-N_A { color: #64748b; }
  footer { margin-top: 36px; color: #94a3b8; font-size: 10px; border-top: 1px solid #e2e8f0; padding-top: 8px; }
  .kv td:first-child { width: 180px; font-weight: 600; color: #334155; }
`;

function page(title: string, body: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>${BASE_CSS}</style></head><body>${body}<footer>${LEGAL} • Generated by Registry.</footer></body></html>`;
}

export interface AssessmentInput {
  tenantName: string;
  generatedAt: string;
  system: AiSystem;
  vendorName?: string;
  answers: ClassificationAnswers;
  classification: ClassificationResult;
  controls: ControlView[];
  gap: SystemGapReport;
}

/** Per-system EU AI Act risk assessment (reproducible reasoning + controls). */
export function assessmentHtml(input: AssessmentInput): string {
  const { system, classification: c, controls, gap } = input;
  const questions = classificationQuestions();
  const qLabel = new Map(questions.map((q) => [q.key, q.prompt]));

  const answerRows = questions
    .map((q) => {
      const raw = input.answers[q.key];
      const shown = typeof raw === "boolean" ? (raw ? "Yes" : "No") : esc(raw ?? "—");
      return `<tr><td>${esc(q.prompt)}</td><td>${shown}</td><td class="cite">${esc(q.citation)}</td></tr>`;
    })
    .join("");

  const traceRows = c.trace
    .map(
      (t) =>
        `<tr><td>${t.order}</td><td>${esc(t.rule_id)}</td><td>${t.matched ? "✓ matched" : "—"}</td><td>${esc(t.tier)}</td><td class="cite">${esc(t.citation)}</td></tr>`,
    )
    .join("");

  const controlRows = controls.length
    ? controls
        .map(
          (ctl) =>
            `<tr><td>${esc(ctl.title)}</td><td class="cite">${esc(ctl.citation)}</td><td class="status-${esc(ctl.status)}">${esc(ctl.status)}</td><td>${esc(ctl.evidence_note ?? "")}</td></tr>`,
        )
        .join("")
    : `<tr><td colspan="4" class="muted">No controls required for this tier.</td></tr>`;

  const notesHtml = c.notes.length
    ? `<h2>Notes</h2><ul>${c.notes.map((n) => `<li>${esc(n)}</li>`).join("")}</ul>`
    : "";

  const body = `
    <h1>AI Risk Assessment — ${esc(system.name)}</h1>
    <div class="muted">${esc(input.tenantName)} • Generated ${esc(input.generatedAt)}</div>
    <p><span class="badge" style="background:${tierColour(c.tier)}">${esc(c.tier)}</span></p>

    <h2>System</h2>
    <table class="kv">
      <tr><td>Vendor</td><td>${esc(input.vendorName ?? "—")}</td></tr>
      <tr><td>Purpose</td><td>${esc(system.purpose)}</td></tr>
      <tr><td>Business owner</td><td>${esc(system.owner)}</td></tr>
      <tr><td>Deployment status</td><td>${esc(system.status)}</td></tr>
      <tr><td>Data categories</td><td>${esc((system.data_categories ?? []).join(", "))}</td></tr>
    </table>

    <h2>Classification</h2>
    <table class="kv">
      <tr><td>Risk tier</td><td><span class="badge" style="background:${tierColour(c.tier)}">${esc(c.tier)}</span></td></tr>
      <tr><td>Deciding rule</td><td>${esc(c.deciding_rule_id ?? "default (minimal)")}</td></tr>
      <tr><td>Primary citation</td><td class="cite">${esc(c.citation)}</td></tr>
      <tr><td>Rationale</td><td>${esc(c.rationale)}</td></tr>
      <tr><td>Classifier version</td><td>${esc(c.classifier_version)}</td></tr>
      <tr><td>Questionnaire version</td><td>${esc(c.questionnaire_version)}</td></tr>
    </table>
    ${notesHtml}

    <h2>Questionnaire answers</h2>
    <table><thead><tr><th>Question</th><th>Answer</th><th>Citation</th></tr></thead><tbody>${answerRows}</tbody></table>

    <h2>Rule evaluation trace (reproducible)</h2>
    <table><thead><tr><th>#</th><th>Rule</th><th>Result</th><th>Tier</th><th>Citation</th></tr></thead><tbody>${traceRows}</tbody></table>

    <h2>Required controls (${gap.satisfied_count}/${gap.required_count} satisfied)</h2>
    <table><thead><tr><th>Control</th><th>Citation</th><th>Status</th><th>Evidence note</th></tr></thead><tbody>${controlRows}</tbody></table>
  `;
  return page(`AI Risk Assessment — ${system.name}`, body);
}

export interface GapReportInput {
  tenantName: string;
  generatedAt: string;
  reports: SystemGapReport[];
}

/** Tenant-wide gap report: what is missing per system's tier. */
export function gapReportHtml(input: GapReportInput): string {
  const rows = input.reports
    .map((r) => {
      if (!r.classified) {
        return `<tr><td>${esc(r.system_name)}</td><td class="muted">Unclassified</td><td class="muted">Run classification</td><td>—</td></tr>`;
      }
      const gaps = r.open_gaps.length
        ? r.open_gaps
            .map((g) => `${esc(g.title)} <span class="cite">(${esc(g.citation)}, ${esc(g.status)})</span>`)
            .join("<br/>")
        : `<span class="status-DONE">Complete</span>`;
      return `<tr><td>${esc(r.system_name)}</td><td><span class="badge" style="background:${tierColour(r.risk_tier ?? "")}">${esc(r.risk_tier)}</span></td><td>${r.satisfied_count}/${r.required_count}</td><td>${gaps}</td></tr>`;
    })
    .join("");

  const body = `
    <h1>AI Governance — Gap Report</h1>
    <div class="muted">${esc(input.tenantName)} • Generated ${esc(input.generatedAt)}</div>
    <h2>Systems (${input.reports.length})</h2>
    <table><thead><tr><th>System</th><th>Tier</th><th>Controls</th><th>Open gaps</th></tr></thead><tbody>${rows}</tbody></table>
  `;
  return page("AI Governance — Gap Report", body);
}
